mkdir -p "usb/Arctic White - Standard";
mkdir -p "usb/Bianca - Standard";
mkdir -p "usb/Desert Sand - Standard";
mkdir -p "usb/Golden Buff - Standard";
mkdir -p "usb/Harvest Cream - Standard";
mkdir -p "usb/Heatherstone - Standard";
mkdir -p "usb/Iron - Standard";
mkdir -p "usb/Kiln Run Brown - Standard";
mkdir -p "usb/Kiln Run Red - Standard";
mkdir -p "usb/Nickel - Standard";
mkdir -p "usb/Okura Cream - Standard";
mkdir -p "usb/Omaha - Standard";
mkdir -p "usb/Palladium - Standard";
mkdir -p "usb/Red - Standard";
mkdir -p "usb/Redbourne - Standard";
mkdir -p "usb/Rumbled Buff - Standard";
mkdir -p "usb/Rumbled Red - Standard";
mkdir -p "usb/Rumbled Grey - Standard";
mkdir -p "usb/Saddlebrown - Standard";
mkdir -p "usb/Sahara - Standard";
mkdir -p "usb/Smooth Red Blend - Standard";
mkdir -p "usb/Soapstone - Standard";
mkdir -p "usb/Steel - Standard";
mkdir -p "usb/Albacore - Mezzo";
mkdir -p "usb/Hoki - Mezzo";
mkdir -p "usb/Mako - Mezzo";
mkdir -p "usb/Nautilus - Mezzo";
mkdir -p "usb/Oyster - Mezzo";
mkdir -p "usb/Cavalli Grey - Presto";
mkdir -p "usb/Kawau Cream - Presto";
mkdir -p "usb/Matakana Cream - Presto";
mkdir -p "usb/Skipjack - Presto";
mkdir -p "usb/Santorini - Block";
mkdir -p "usb/Jervois - Metro";
mkdir -p "usb/Richmond - Metro";
mkdir -p "usb/Thorndon - Metro";
mkdir -p "usb/Sumner - Metro";
cd usb
touch "Arctic White - Standard/Arctic White - Standard - White Mortar.png";
touch "Bianca - Standard/Bianca - Standard - White Mortar.png";
touch "Desert Sand - Standard/Desert Sand - Standard - White Mortar.png";
touch "Golden Buff - Standard/Golden Buff - Standard - White Mortar.png";
touch "Harvest Cream - Standard/Harvest Cream - Standard - White Mortar.png";
touch "Heatherstone - Standard/Heatherstone - Standard - White Mortar.png";
touch "Iron - Standard/Iron - Standard - White Mortar.png";
touch "Kiln Run Brown - Standard/Kiln Run Brown - Standard - White Mortar.png";
touch "Kiln Run Red - Standard/Kiln Run Red - Standard - White Mortar.png";
touch "Nickel - Standard/Nickel - Standard - White Mortar.png";
touch "Okura Cream - Standard/Okura Cream - Standard - White Mortar.png";
touch "Omaha - Standard/Omaha - Standard - White Mortar.png";
touch "Palladium - Standard/Palladium - Standard - White Mortar.png";
touch "Red - Standard/Red - Standard - White Mortar.png";
touch "Redbourne - Standard/Redbourne - Standard - White Mortar.png";
touch "Rumbled Buff - Standard/Rumbled Buff - Standard - White Mortar.png";
touch "Rumbled Red - Standard/Rumbled Red - Standard - White Mortar.png";
touch "Rumbled Grey - Standard/Rumbled Grey - Standard - White Mortar.png";
touch "Saddlebrown - Standard/Saddlebrown - Standard - White Mortar.png";
touch "Sahara - Standard/Sahara - Standard - White Mortar.png";
touch "Smooth Red Blend - Standard/Smooth Red Blend - Standard - White Mortar.png";
touch "Soapstone - Standard/Soapstone - Standard - White Mortar.png";
touch "Steel - Standard/Steel - Standard - White Mortar.png";
touch "Albacore - Mezzo/Albacore - Mezzo - White Mortar.png";
touch "Hoki - Mezzo/Hoki - Mezzo - White Mortar.png";
touch "Mako - Mezzo/Mako - Mezzo - White Mortar.png";
touch "Nautilus - Mezzo/Nautilus - Mezzo - White Mortar.png";
touch "Oyster - Mezzo/Oyster - Mezzo - White Mortar.png";
touch "Cavalli Grey - Presto/Cavalli Grey - Presto - White Mortar.png";
touch "Kawau Cream - Presto/Kawau Cream - Presto - White Mortar.png";
touch "Matakana Cream - Presto/Matakana Cream - Presto - White Mortar.png";
touch "Skipjack - Presto/Skipjack - Presto - White Mortar.png";
touch "Santorini - Block/Santorini - Block - White Mortar.png";
touch "Jervois - Metro/Jervois - Metro - White Mortar.png";
touch "Richmond - Metro/Richmond - Metro - White Mortar.png";
touch "Thorndon - Metro/Thorndon - Metro - White Mortar.png";
touch "Sumner - Metro/Sumner - Metro - White Mortar.png";
touch "Arctic White - Standard/Arctic White - Standard - Dark Grey Mortar.png";
touch "Bianca - Standard/Bianca - Standard - Dark Grey Mortar.png";
touch "Desert Sand - Standard/Desert Sand - Standard - Dark Grey Mortar.png";
touch "Golden Buff - Standard/Golden Buff - Standard - Dark Grey Mortar.png";
touch "Harvest Cream - Standard/Harvest Cream - Standard - Dark Grey Mortar.png";
touch "Heatherstone - Standard/Heatherstone - Standard - Dark Grey Mortar.png";
touch "Iron - Standard/Iron - Standard - Dark Grey Mortar.png";
touch "Kiln Run Brown - Standard/Kiln Run Brown - Standard - Dark Grey Mortar.png";
touch "Kiln Run Red - Standard/Kiln Run Red - Standard - Dark Grey Mortar.png";
touch "Nickel - Standard/Nickel - Standard - Dark Grey Mortar.png";
touch "Okura Cream - Standard/Okura Cream - Standard - Dark Grey Mortar.png";
touch "Omaha - Standard/Omaha - Standard - Dark Grey Mortar.png";
touch "Palladium - Standard/Palladium - Standard - Dark Grey Mortar.png";
touch "Red - Standard/Red - Standard - Dark Grey Mortar.png";
touch "Redbourne - Standard/Redbourne - Standard - Dark Grey Mortar.png";
touch "Rumbled Buff - Standard/Rumbled Buff - Standard - Dark Grey Mortar.png";
touch "Rumbled Red - Standard/Rumbled Red - Standard - Dark Grey Mortar.png";
touch "Rumbled Grey - Standard/Rumbled Grey - Standard - Dark Grey Mortar.png";
touch "Saddlebrown - Standard/Saddlebrown - Standard - Dark Grey Mortar.png";
touch "Sahara - Standard/Sahara - Standard - Dark Grey Mortar.png";
touch "Smooth Red Blend - Standard/Smooth Red Blend - Standard - Dark Grey Mortar.png";
touch "Soapstone - Standard/Soapstone - Standard - Dark Grey Mortar.png";
touch "Steel - Standard/Steel - Standard - Dark Grey Mortar.png";
touch "Albacore - Mezzo/Albacore - Mezzo - Dark Grey Mortar.png";
touch "Hoki - Mezzo/Hoki - Mezzo - Dark Grey Mortar.png";
touch "Mako - Mezzo/Mako - Mezzo - Dark Grey Mortar.png";
touch "Nautilus - Mezzo/Nautilus - Mezzo - Dark Grey Mortar.png";
touch "Oyster - Mezzo/Oyster - Mezzo - Dark Grey Mortar.png";
touch "Cavalli Grey - Presto/Cavalli Grey - Presto - Dark Grey Mortar.png";
touch "Kawau Cream - Presto/Kawau Cream - Presto - Dark Grey Mortar.png";
touch "Matakana Cream - Presto/Matakana Cream - Presto - Dark Grey Mortar.png";
touch "Skipjack - Presto/Skipjack - Presto - Dark Grey Mortar.png";
touch "Santorini - Block/Santorini - Block - Dark Grey Mortar.png";
touch "Jervois - Metro/Jervois - Metro - Dark Grey Mortar.png";
touch "Richmond - Metro/Richmond - Metro - Dark Grey Mortar.png";
touch "Thorndon - Metro/Thorndon - Metro - Dark Grey Mortar.png";
touch "Sumner - Metro/Sumner - Metro - Dark Grey Mortar.png";
touch "Arctic White - Standard/Arctic White - Standard - Standard Mortar.png";
touch "Bianca - Standard/Bianca - Standard - Standard Mortar.png";
touch "Desert Sand - Standard/Desert Sand - Standard - Standard Mortar.png";
touch "Golden Buff - Standard/Golden Buff - Standard - Standard Mortar.png";
touch "Harvest Cream - Standard/Harvest Cream - Standard - Standard Mortar.png";
touch "Heatherstone - Standard/Heatherstone - Standard - Standard Mortar.png";
touch "Iron - Standard/Iron - Standard - Standard Mortar.png";
touch "Kiln Run Brown - Standard/Kiln Run Brown - Standard - Standard Mortar.png";
touch "Kiln Run Red - Standard/Kiln Run Red - Standard - Standard Mortar.png";
touch "Nickel - Standard/Nickel - Standard - Standard Mortar.png";
touch "Okura Cream - Standard/Okura Cream - Standard - Standard Mortar.png";
touch "Omaha - Standard/Omaha - Standard - Standard Mortar.png";
touch "Palladium - Standard/Palladium - Standard - Standard Mortar.png";
touch "Red - Standard/Red - Standard - Standard Mortar.png";
touch "Redbourne - Standard/Redbourne - Standard - Standard Mortar.png";
touch "Rumbled Buff - Standard/Rumbled Buff - Standard - Standard Mortar.png";
touch "Rumbled Red - Standard/Rumbled Red - Standard - Standard Mortar.png";
touch "Rumbled Grey - Standard/Rumbled Grey - Standard - Standard Mortar.png";
touch "Saddlebrown - Standard/Saddlebrown - Standard - Standard Mortar.png";
touch "Sahara - Standard/Sahara - Standard - Standard Mortar.png";
touch "Smooth Red Blend - Standard/Smooth Red Blend - Standard - Standard Mortar.png";
touch "Soapstone - Standard/Soapstone - Standard - Standard Mortar.png";
touch "Steel - Standard/Steel - Standard - Standard Mortar.png";
touch "Albacore - Mezzo/Albacore - Mezzo - Standard Mortar.png";
touch "Hoki - Mezzo/Hoki - Mezzo - Standard Mortar.png";
touch "Mako - Mezzo/Mako - Mezzo - Standard Mortar.png";
touch "Nautilus - Mezzo/Nautilus - Mezzo - Standard Mortar.png";
touch "Oyster - Mezzo/Oyster - Mezzo - Standard Mortar.png";
touch "Cavalli Grey - Presto/Cavalli Grey - Presto - Standard Mortar.png";
touch "Kawau Cream - Presto/Kawau Cream - Presto - Standard Mortar.png";
touch "Matakana Cream - Presto/Matakana Cream - Presto - Standard Mortar.png";
touch "Skipjack - Presto/Skipjack - Presto - Standard Mortar.png";
touch "Santorini - Block/Santorini - Block - Standard Mortar.png";
touch "Jervois - Metro/Jervois - Metro - Standard Mortar.png";
touch "Richmond - Metro/Richmond - Metro - Standard Mortar.png";
touch "Thorndon - Metro/Thorndon - Metro - Standard Mortar.png";
touch "Sumner - Metro/Sumner - Metro - Standard Mortar.png";
touch "Arctic White - Standard/Arctic White - Standard - Cream Mortar.png";
touch "Bianca - Standard/Bianca - Standard - Cream Mortar.png";
touch "Desert Sand - Standard/Desert Sand - Standard - Cream Mortar.png";
touch "Golden Buff - Standard/Golden Buff - Standard - Cream Mortar.png";
touch "Harvest Cream - Standard/Harvest Cream - Standard - Cream Mortar.png";
touch "Heatherstone - Standard/Heatherstone - Standard - Cream Mortar.png";
touch "Iron - Standard/Iron - Standard - Cream Mortar.png";
touch "Kiln Run Brown - Standard/Kiln Run Brown - Standard - Cream Mortar.png";
touch "Kiln Run Red - Standard/Kiln Run Red - Standard - Cream Mortar.png";
touch "Nickel - Standard/Nickel - Standard - Cream Mortar.png";
touch "Okura Cream - Standard/Okura Cream - Standard - Cream Mortar.png";
touch "Omaha - Standard/Omaha - Standard - Cream Mortar.png";
touch "Palladium - Standard/Palladium - Standard - Cream Mortar.png";
touch "Red - Standard/Red - Standard - Cream Mortar.png";
touch "Redbourne - Standard/Redbourne - Standard - Cream Mortar.png";
touch "Rumbled Buff - Standard/Rumbled Buff - Standard - Cream Mortar.png";
touch "Rumbled Red - Standard/Rumbled Red - Standard - Cream Mortar.png";
touch "Rumbled Grey - Standard/Rumbled Grey - Standard - Cream Mortar.png";
touch "Saddlebrown - Standard/Saddlebrown - Standard - Cream Mortar.png";
touch "Sahara - Standard/Sahara - Standard - Cream Mortar.png";
touch "Smooth Red Blend - Standard/Smooth Red Blend - Standard - Cream Mortar.png";
touch "Soapstone - Standard/Soapstone - Standard - Cream Mortar.png";
touch "Steel - Standard/Steel - Standard - Cream Mortar.png";
touch "Albacore - Mezzo/Albacore - Mezzo - Cream Mortar.png";
touch "Hoki - Mezzo/Hoki - Mezzo - Cream Mortar.png";
touch "Mako - Mezzo/Mako - Mezzo - Cream Mortar.png";
touch "Nautilus - Mezzo/Nautilus - Mezzo - Cream Mortar.png";
touch "Oyster - Mezzo/Oyster - Mezzo - Cream Mortar.png";
touch "Cavalli Grey - Presto/Cavalli Grey - Presto - Cream Mortar.png";
touch "Kawau Cream - Presto/Kawau Cream - Presto - Cream Mortar.png";
touch "Matakana Cream - Presto/Matakana Cream - Presto - Cream Mortar.png";
touch "Skipjack - Presto/Skipjack - Presto - Cream Mortar.png";
touch "Santorini - Block/Santorini - Block - Cream Mortar.png";
touch "Jervois - Metro/Jervois - Metro - Cream Mortar.png";
touch "Richmond - Metro/Richmond - Metro - Cream Mortar.png";
touch "Thorndon - Metro/Thorndon - Metro - Cream Mortar.png";
touch "Sumner - Metro/Sumner - Metro - Cream Mortar.png";
cd ../

composite -compose Atop -tile mortar_cream.png standard/standard_cut.png standard/mortar_cream.png
composite -compose Atop -tile mortar_dark.png standard/standard_cut.png standard/mortar_dark.png
composite -compose Atop -tile mortar_standard.png standard/standard_cut.png standard/mortar_standard.png
composite -compose Atop -tile mortar_white.png standard/standard_cut.png standard/mortar_white.png
composite -compose Atop -tile mortar_cream.png mezzo/mezzo_cut.png mezzo/mortar_cream.png
composite -compose Atop -tile mortar_dark.png mezzo/mezzo_cut.png mezzo/mortar_dark.png
composite -compose Atop -tile mortar_standard.png mezzo/mezzo_cut.png mezzo/mortar_standard.png
composite -compose Atop -tile mortar_white.png mezzo/mezzo_cut.png mezzo/mortar_white.png
composite -compose Atop -tile mortar_cream.png presto/presto_cut.png presto/mortar_cream.png
composite -compose Atop -tile mortar_dark.png presto/presto_cut.png presto/mortar_dark.png
composite -compose Atop -tile mortar_standard.png presto/presto_cut.png presto/mortar_standard.png
composite -compose Atop -tile mortar_white.png presto/presto_cut.png presto/mortar_white.png
composite -compose Atop -tile mortar_cream.png block/block_cut.png block/mortar_cream.png
composite -compose Atop -tile mortar_dark.png block/block_cut.png block/mortar_dark.png
composite -compose Atop -tile mortar_standard.png block/block_cut.png block/mortar_standard.png
composite -compose Atop -tile mortar_white.png block/block_cut.png block/mortar_white.png
composite -compose Atop -tile mortar_cream.png metro/metro_cut.png metro/mortar_cream.png
composite -compose Atop -tile mortar_dark.png metro/metro_cut.png metro/mortar_dark.png
composite -compose Atop -tile mortar_standard.png metro/metro_cut.png metro/mortar_standard.png
composite -compose Atop -tile mortar_white.png metro/metro_cut.png metro/mortar_white.png

composite -compose Over -tile "standard/mortar_white.png" "standard/arctic_white_DIFFUSE.png" "usb/Arctic White - Standard/Arctic White - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/bianca_DIFFUSE.png" "usb/Bianca - Standard/Bianca - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/desert_sand_DIFFUSE.png" "usb/Desert Sand - Standard/Desert Sand - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/golden_buff_DIFFUSE.png" "usb/Golden Buff - Standard/Golden Buff - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/harvest_cream_DIFFUSE.png" "usb/Harvest Cream - Standard/Harvest Cream - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/heatherstone_DIFFUSE.png" "usb/Heatherstone - Standard/Heatherstone - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/iron_DIFFUSE.png" "usb/Iron - Standard/Iron - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/kiln_run_brown_DIFFUSE.png" "usb/Kiln Run Brown - Standard/Kiln Run Brown - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/kiln_run_red_DIFFUSE.png" "usb/Kiln Run Red - Standard/Kiln Run Red - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/nickel_DIFFUSE.png" "usb/Nickel - Standard/Nickel - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/okura_cream_DIFFUSE.png" "usb/Okura Cream - Standard/Okura Cream - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/omaha_DIFFUSE.png" "usb/Omaha - Standard/Omaha - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/palladium_DIFFUSE.png" "usb/Palladium - Standard/Palladium - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/red_DIFFUSE.png" "usb/Red - Standard/Red - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/redbourne_DIFFUSE.png" "usb/Redbourne - Standard/Redbourne - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/rumbled_buff_DIFFUSE.png" "usb/Rumbled Buff - Standard/Rumbled Buff - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/rumbled_red_DIFFUSE.png" "usb/Rumbled Red - Standard/Rumbled Red - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/rumbled_grey_DIFFUSE.png" "usb/Rumbled Grey - Standard/Rumbled Grey - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/saddlebrown_DIFFUSE.png" "usb/Saddlebrown - Standard/Saddlebrown - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/sahara_DIFFUSE.png" "usb/Sahara - Standard/Sahara - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/smooth_red_blend_DIFFUSE.png" "usb/Smooth Red Blend - Standard/Smooth Red Blend - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/soapstone_DIFFUSE.png" "usb/Soapstone - Standard/Soapstone - Standard - White Mortar.png";
composite -compose Over -tile "standard/mortar_white.png" "standard/steel_DIFFUSE.png" "usb/Steel - Standard/Steel - Standard - White Mortar.png";
composite -compose Over -tile "mezzo/mortar_white.png" "mezzo/albacore_DIFFUSE.png" "usb/Albacore - Mezzo/Albacore - Mezzo - White Mortar.png";
composite -compose Over -tile "mezzo/mortar_white.png" "mezzo/hoki_DIFFUSE.png" "usb/Hoki - Mezzo/Hoki - Mezzo - White Mortar.png";
composite -compose Over -tile "mezzo/mortar_white.png" "mezzo/mako_DIFFUSE.png" "usb/Mako - Mezzo/Mako - Mezzo - White Mortar.png";
composite -compose Over -tile "mezzo/mortar_white.png" "mezzo/nautilus_DIFFUSE.png" "usb/Nautilus - Mezzo/Nautilus - Mezzo - White Mortar.png";
composite -compose Over -tile "mezzo/mortar_white.png" "mezzo/oyster_DIFFUSE.png" "usb/Oyster - Mezzo/Oyster - Mezzo - White Mortar.png";
composite -compose Over -tile "presto/mortar_white.png" "presto/cavalli_grey_DIFFUSE.png" "usb/Cavalli Grey - Presto/Cavalli Grey - Presto - White Mortar.png";
composite -compose Over -tile "presto/mortar_white.png" "presto/kawau_cream_DIFFUSE.png" "usb/Kawau Cream - Presto/Kawau Cream - Presto - White Mortar.png";
composite -compose Over -tile "presto/mortar_white.png" "presto/matakana_cream_DIFFUSE.png" "usb/Matakana Cream - Presto/Matakana Cream - Presto - White Mortar.png";
composite -compose Over -tile "presto/mortar_white.png" "presto/skipjack_DIFFUSE.png" "usb/Skipjack - Presto/Skipjack - Presto - White Mortar.png";
composite -compose Over -tile "block/mortar_white.png" "block/santorini_DIFFUSE.png" "usb/Santorini - Block/Santorini - Block - White Mortar.png";
composite -compose Over -tile "metro/mortar_white.png" "metro/jervois_DIFFUSE.png" "usb/Jervois - Metro/Jervois - Metro - White Mortar.png";
composite -compose Over -tile "metro/mortar_white.png" "metro/richmond_DIFFUSE.png" "usb/Richmond - Metro/Richmond - Metro - White Mortar.png";
composite -compose Over -tile "metro/mortar_white.png" "metro/thorndon_DIFFUSE.png" "usb/Thorndon - Metro/Thorndon - Metro - White Mortar.png";
composite -compose Over -tile "metro/mortar_white.png" "metro/sumner_DIFFUSE.png" "usb/Sumner - Metro/Sumner - Metro - White Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/arctic_white_DIFFUSE.png" "usb/Arctic White - Standard/Arctic White - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/bianca_DIFFUSE.png" "usb/Bianca - Standard/Bianca - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/desert_sand_DIFFUSE.png" "usb/Desert Sand - Standard/Desert Sand - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/golden_buff_DIFFUSE.png" "usb/Golden Buff - Standard/Golden Buff - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/harvest_cream_DIFFUSE.png" "usb/Harvest Cream - Standard/Harvest Cream - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/heatherstone_DIFFUSE.png" "usb/Heatherstone - Standard/Heatherstone - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/iron_DIFFUSE.png" "usb/Iron - Standard/Iron - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/kiln_run_brown_DIFFUSE.png" "usb/Kiln Run Brown - Standard/Kiln Run Brown - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/kiln_run_red_DIFFUSE.png" "usb/Kiln Run Red - Standard/Kiln Run Red - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/nickel_DIFFUSE.png" "usb/Nickel - Standard/Nickel - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/okura_cream_DIFFUSE.png" "usb/Okura Cream - Standard/Okura Cream - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/omaha_DIFFUSE.png" "usb/Omaha - Standard/Omaha - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/palladium_DIFFUSE.png" "usb/Palladium - Standard/Palladium - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/red_DIFFUSE.png" "usb/Red - Standard/Red - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/redbourne_DIFFUSE.png" "usb/Redbourne - Standard/Redbourne - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/rumbled_buff_DIFFUSE.png" "usb/Rumbled Buff - Standard/Rumbled Buff - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/rumbled_red_DIFFUSE.png" "usb/Rumbled Red - Standard/Rumbled Red - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/rumbled_grey_DIFFUSE.png" "usb/Rumbled Grey - Standard/Rumbled Grey - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/saddlebrown_DIFFUSE.png" "usb/Saddlebrown - Standard/Saddlebrown - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/sahara_DIFFUSE.png" "usb/Sahara - Standard/Sahara - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/smooth_red_blend_DIFFUSE.png" "usb/Smooth Red Blend - Standard/Smooth Red Blend - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/soapstone_DIFFUSE.png" "usb/Soapstone - Standard/Soapstone - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_dark.png" "standard/steel_DIFFUSE.png" "usb/Steel - Standard/Steel - Standard - Dark Grey Mortar.png";
composite -compose Over -tile "mezzo/mortar_dark.png" "mezzo/albacore_DIFFUSE.png" "usb/Albacore - Mezzo/Albacore - Mezzo - Dark Grey Mortar.png";
composite -compose Over -tile "mezzo/mortar_dark.png" "mezzo/hoki_DIFFUSE.png" "usb/Hoki - Mezzo/Hoki - Mezzo - Dark Grey Mortar.png";
composite -compose Over -tile "mezzo/mortar_dark.png" "mezzo/mako_DIFFUSE.png" "usb/Mako - Mezzo/Mako - Mezzo - Dark Grey Mortar.png";
composite -compose Over -tile "mezzo/mortar_dark.png" "mezzo/nautilus_DIFFUSE.png" "usb/Nautilus - Mezzo/Nautilus - Mezzo - Dark Grey Mortar.png";
composite -compose Over -tile "mezzo/mortar_dark.png" "mezzo/oyster_DIFFUSE.png" "usb/Oyster - Mezzo/Oyster - Mezzo - Dark Grey Mortar.png";
composite -compose Over -tile "presto/mortar_dark.png" "presto/cavalli_grey_DIFFUSE.png" "usb/Cavalli Grey - Presto/Cavalli Grey - Presto - Dark Grey Mortar.png";
composite -compose Over -tile "presto/mortar_dark.png" "presto/kawau_cream_DIFFUSE.png" "usb/Kawau Cream - Presto/Kawau Cream - Presto - Dark Grey Mortar.png";
composite -compose Over -tile "presto/mortar_dark.png" "presto/matakana_cream_DIFFUSE.png" "usb/Matakana Cream - Presto/Matakana Cream - Presto - Dark Grey Mortar.png";
composite -compose Over -tile "presto/mortar_dark.png" "presto/skipjack_DIFFUSE.png" "usb/Skipjack - Presto/Skipjack - Presto - Dark Grey Mortar.png";
composite -compose Over -tile "block/mortar_dark.png" "block/santorini_DIFFUSE.png" "usb/Santorini - Block/Santorini - Block - Dark Grey Mortar.png";
composite -compose Over -tile "metro/mortar_dark.png" "metro/jervois_DIFFUSE.png" "usb/Jervois - Metro/Jervois - Metro - Dark Grey Mortar.png";
composite -compose Over -tile "metro/mortar_dark.png" "metro/richmond_DIFFUSE.png" "usb/Richmond - Metro/Richmond - Metro - Dark Grey Mortar.png";
composite -compose Over -tile "metro/mortar_dark.png" "metro/thorndon_DIFFUSE.png" "usb/Thorndon - Metro/Thorndon - Metro - Dark Grey Mortar.png";
composite -compose Over -tile "metro/mortar_dark.png" "metro/sumner_DIFFUSE.png" "usb/Sumner - Metro/Sumner - Metro - Dark Grey Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/arctic_white_DIFFUSE.png" "usb/Arctic White - Standard/Arctic White - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/bianca_DIFFUSE.png" "usb/Bianca - Standard/Bianca - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/desert_sand_DIFFUSE.png" "usb/Desert Sand - Standard/Desert Sand - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/golden_buff_DIFFUSE.png" "usb/Golden Buff - Standard/Golden Buff - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/harvest_cream_DIFFUSE.png" "usb/Harvest Cream - Standard/Harvest Cream - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/heatherstone_DIFFUSE.png" "usb/Heatherstone - Standard/Heatherstone - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/iron_DIFFUSE.png" "usb/Iron - Standard/Iron - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/kiln_run_brown_DIFFUSE.png" "usb/Kiln Run Brown - Standard/Kiln Run Brown - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/kiln_run_red_DIFFUSE.png" "usb/Kiln Run Red - Standard/Kiln Run Red - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/nickel_DIFFUSE.png" "usb/Nickel - Standard/Nickel - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/okura_cream_DIFFUSE.png" "usb/Okura Cream - Standard/Okura Cream - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/omaha_DIFFUSE.png" "usb/Omaha - Standard/Omaha - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/palladium_DIFFUSE.png" "usb/Palladium - Standard/Palladium - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/red_DIFFUSE.png" "usb/Red - Standard/Red - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/redbourne_DIFFUSE.png" "usb/Redbourne - Standard/Redbourne - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/rumbled_buff_DIFFUSE.png" "usb/Rumbled Buff - Standard/Rumbled Buff - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/rumbled_red_DIFFUSE.png" "usb/Rumbled Red - Standard/Rumbled Red - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/rumbled_grey_DIFFUSE.png" "usb/Rumbled Grey - Standard/Rumbled Grey - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/saddlebrown_DIFFUSE.png" "usb/Saddlebrown - Standard/Saddlebrown - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/sahara_DIFFUSE.png" "usb/Sahara - Standard/Sahara - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/smooth_red_blend_DIFFUSE.png" "usb/Smooth Red Blend - Standard/Smooth Red Blend - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/soapstone_DIFFUSE.png" "usb/Soapstone - Standard/Soapstone - Standard - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_standard.png" "standard/steel_DIFFUSE.png" "usb/Steel - Standard/Steel - Standard - Standard Mortar.png";
composite -compose Over -tile "mezzo/mortar_standard.png" "mezzo/albacore_DIFFUSE.png" "usb/Albacore - Mezzo/Albacore - Mezzo - Standard Mortar.png";
composite -compose Over -tile "mezzo/mortar_standard.png" "mezzo/hoki_DIFFUSE.png" "usb/Hoki - Mezzo/Hoki - Mezzo - Standard Mortar.png";
composite -compose Over -tile "mezzo/mortar_standard.png" "mezzo/mako_DIFFUSE.png" "usb/Mako - Mezzo/Mako - Mezzo - Standard Mortar.png";
composite -compose Over -tile "mezzo/mortar_standard.png" "mezzo/nautilus_DIFFUSE.png" "usb/Nautilus - Mezzo/Nautilus - Mezzo - Standard Mortar.png";
composite -compose Over -tile "mezzo/mortar_standard.png" "mezzo/oyster_DIFFUSE.png" "usb/Oyster - Mezzo/Oyster - Mezzo - Standard Mortar.png";
composite -compose Over -tile "presto/mortar_standard.png" "presto/cavalli_grey_DIFFUSE.png" "usb/Cavalli Grey - Presto/Cavalli Grey - Presto - Standard Mortar.png";
composite -compose Over -tile "presto/mortar_standard.png" "presto/kawau_cream_DIFFUSE.png" "usb/Kawau Cream - Presto/Kawau Cream - Presto - Standard Mortar.png";
composite -compose Over -tile "presto/mortar_standard.png" "presto/matakana_cream_DIFFUSE.png" "usb/Matakana Cream - Presto/Matakana Cream - Presto - Standard Mortar.png";
composite -compose Over -tile "presto/mortar_standard.png" "presto/skipjack_DIFFUSE.png" "usb/Skipjack - Presto/Skipjack - Presto - Standard Mortar.png";
composite -compose Over -tile "block/mortar_standard.png" "block/santorini_DIFFUSE.png" "usb/Santorini - Block/Santorini - Block - Standard Mortar.png";
composite -compose Over -tile "metro/mortar_standard.png" "metro/jervois_DIFFUSE.png" "usb/Jervois - Metro/Jervois - Metro - Standard Mortar.png";
composite -compose Over -tile "metro/mortar_standard.png" "metro/richmond_DIFFUSE.png" "usb/Richmond - Metro/Richmond - Metro - Standard Mortar.png";
composite -compose Over -tile "metro/mortar_standard.png" "metro/thorndon_DIFFUSE.png" "usb/Thorndon - Metro/Thorndon - Metro - Standard Mortar.png";
composite -compose Over -tile "metro/mortar_standard.png" "metro/sumner_DIFFUSE.png" "usb/Sumner - Metro/Sumner - Metro - Standard Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/arctic_white_DIFFUSE.png" "usb/Arctic White - Standard/Arctic White - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/bianca_DIFFUSE.png" "usb/Bianca - Standard/Bianca - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/desert_sand_DIFFUSE.png" "usb/Desert Sand - Standard/Desert Sand - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/golden_buff_DIFFUSE.png" "usb/Golden Buff - Standard/Golden Buff - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/harvest_cream_DIFFUSE.png" "usb/Harvest Cream - Standard/Harvest Cream - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/heatherstone_DIFFUSE.png" "usb/Heatherstone - Standard/Heatherstone - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/iron_DIFFUSE.png" "usb/Iron - Standard/Iron - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/kiln_run_brown_DIFFUSE.png" "usb/Kiln Run Brown - Standard/Kiln Run Brown - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/kiln_run_red_DIFFUSE.png" "usb/Kiln Run Red - Standard/Kiln Run Red - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/nickel_DIFFUSE.png" "usb/Nickel - Standard/Nickel - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/okura_cream_DIFFUSE.png" "usb/Okura Cream - Standard/Okura Cream - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/omaha_DIFFUSE.png" "usb/Omaha - Standard/Omaha - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/palladium_DIFFUSE.png" "usb/Palladium - Standard/Palladium - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/red_DIFFUSE.png" "usb/Red - Standard/Red - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/redbourne_DIFFUSE.png" "usb/Redbourne - Standard/Redbourne - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/rumbled_buff_DIFFUSE.png" "usb/Rumbled Buff - Standard/Rumbled Buff - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/rumbled_red_DIFFUSE.png" "usb/Rumbled Red - Standard/Rumbled Red - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/rumbled_grey_DIFFUSE.png" "usb/Rumbled Grey - Standard/Rumbled Grey - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/saddlebrown_DIFFUSE.png" "usb/Saddlebrown - Standard/Saddlebrown - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/sahara_DIFFUSE.png" "usb/Sahara - Standard/Sahara - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/smooth_red_blend_DIFFUSE.png" "usb/Smooth Red Blend - Standard/Smooth Red Blend - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/soapstone_DIFFUSE.png" "usb/Soapstone - Standard/Soapstone - Standard - Cream Mortar.png";
composite -compose Over -tile "standard/mortar_cream.png" "standard/steel_DIFFUSE.png" "usb/Steel - Standard/Steel - Standard - Cream Mortar.png";
composite -compose Over -tile "mezzo/mortar_cream.png" "mezzo/albacore_DIFFUSE.png" "usb/Albacore - Mezzo/Albacore - Mezzo - Cream Mortar.png";
composite -compose Over -tile "mezzo/mortar_cream.png" "mezzo/hoki_DIFFUSE.png" "usb/Hoki - Mezzo/Hoki - Mezzo - Cream Mortar.png";
composite -compose Over -tile "mezzo/mortar_cream.png" "mezzo/mako_DIFFUSE.png" "usb/Mako - Mezzo/Mako - Mezzo - Cream Mortar.png";
composite -compose Over -tile "mezzo/mortar_cream.png" "mezzo/nautilus_DIFFUSE.png" "usb/Nautilus - Mezzo/Nautilus - Mezzo - Cream Mortar.png";
composite -compose Over -tile "mezzo/mortar_cream.png" "mezzo/oyster_DIFFUSE.png" "usb/Oyster - Mezzo/Oyster - Mezzo - Cream Mortar.png";
composite -compose Over -tile "presto/mortar_cream.png" "presto/cavalli_grey_DIFFUSE.png" "usb/Cavalli Grey - Presto/Cavalli Grey - Presto - Cream Mortar.png";
composite -compose Over -tile "presto/mortar_cream.png" "presto/kawau_cream_DIFFUSE.png" "usb/Kawau Cream - Presto/Kawau Cream - Presto - Cream Mortar.png";
composite -compose Over -tile "presto/mortar_cream.png" "presto/matakana_cream_DIFFUSE.png" "usb/Matakana Cream - Presto/Matakana Cream - Presto - Cream Mortar.png";
composite -compose Over -tile "presto/mortar_cream.png" "presto/skipjack_DIFFUSE.png" "usb/Skipjack - Presto/Skipjack - Presto - Cream Mortar.png";
composite -compose Over -tile "block/mortar_cream.png" "block/santorini_DIFFUSE.png" "usb/Santorini - Block/Santorini - Block - Cream Mortar.png";
composite -compose Over -tile "metro/mortar_cream.png" "metro/jervois_DIFFUSE.png" "usb/Jervois - Metro/Jervois - Metro - Cream Mortar.png";
composite -compose Over -tile "metro/mortar_cream.png" "metro/richmond_DIFFUSE.png" "usb/Richmond - Metro/Richmond - Metro - Cream Mortar.png";
composite -compose Over -tile "metro/mortar_cream.png" "metro/thorndon_DIFFUSE.png" "usb/Thorndon - Metro/Thorndon - Metro - Cream Mortar.png";
composite -compose Over -tile "metro/mortar_cream.png" "metro/sumner_DIFFUSE.png" "usb/Sumner - Metro/Sumner - Metro - Cream Mortar.png";
